lang:
    name: Ouch
    disable: is now disabled.
    enable: Enabled.
    break: Ouch.
    place: Ahhhhh.....

#lang:
#    name: Aie
#    disable: est maintenant désactivé
#    enable: Activé
#    break: Aie.
#    place: Ahhhhh.....